/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChildrenRouteImport } from './routes/children'
import { Route as RedemptionsRouteImport } from './routes/redemptions'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as TasksRouteImport } from './routes/tasks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildrenRoute = ChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => rootRouteImport,
} as any)
const RedemptionsRoute = RedemptionsRouteImport.update({
  id: '/redemptions',
  path: '/redemptions',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/children': typeof ChildrenRoute
  '/redemptions': typeof RedemptionsRoute
  '/rewards': typeof RewardsRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/children': typeof ChildrenRoute
  '/redemptions': typeof RedemptionsRoute
  '/rewards': typeof RewardsRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/children': typeof ChildrenRoute
  '/redemptions': typeof RedemptionsRoute
  '/rewards': typeof RewardsRoute
  '/tasks': typeof TasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/children' | '/redemptions' | '/rewards' | '/tasks'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/children' | '/redemptions' | '/rewards' | '/tasks'
  id: '__root__' | '/' | '/children' | '/redemptions' | '/rewards' | '/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChildrenRoute: typeof ChildrenRoute
  RedemptionsRoute: typeof RedemptionsRoute
  RewardsRoute: typeof RewardsRoute
  TasksRoute: typeof TasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/children': {
      id: '/children'
      path: '/children'
      fullPath: '/children'
      preLoaderRoute: typeof ChildrenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redemptions': {
      id: '/redemptions'
      path: '/redemptions'
      fullPath: '/redemptions'
      preLoaderRoute: typeof RedemptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChildrenRoute: ChildrenRoute,
  RedemptionsRoute: RedemptionsRoute,
  RewardsRoute: RewardsRoute,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
